sudo: false
language: python
matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      python: 3.7
    - env: TOXENV=py38
      python: 3.8
    - env: TOXENV=py39
      python: 3.9
    - env: TOXENV=pypy
      python: pypy
    - env: TOXENV=pypy3
      python: pypy3
    - env: TOXENV=flake8
    - env: TOXENV=docs
      before_install: gem install mdl
install:
  - pip install tox
script:
  - tox
branches:
  only:
    - master
notifications:
  email: false
